[features]
no-idl = []
no-log-ix = []
cpi = true

[programs.devnet]
complifi = "8n1D2rYYeUnfrWN4qTDHAvvbEokbPop6cbeSNZ3brNeU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
# Limit to our actual test file to avoid picking up .d.ts
 test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/complifi.ts"

[test]
startup_wait = 10000

[workspace]
members = [
	"programs/*"
]

[build]
version = "0.32.1"

[toolchain]
anchor_version = "0.32.1"
