[features]
no-idl = []
no-log-ix = []
cpi = true

[programs.localnet]
complifi = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 10000

[workspace]
members = [
    "programs/*"
]

[build]
version = "0.29.0"

[toolchain]
anchor_version = "0.29.0"

